### PR TITLE
updated countdown

### PR DESCRIPTION
**Pull request by victorhck**
Hello.

I update the countdown to the new Leap 42.2 release Nov 16th.
Please check if the artwork and everything else it's right.

've phun!

### CODE REVIEW

**Comment by lnussel** [comment]
thanks but could you please write the commit message in english?

**Comment by tampakrap** [comment]
reopenning, he can update the commit message in the same pull request

**Comment by victorhck** [comment]
Sorry for that! I didn't realize.
I have changed the text with: `git` commit --ammend `"new_text"`
check if now it's ok...

**Comment by lnussel** [comment]
Sí, gracias! You may want to talk to darix to deploy

**Pull request merged**
